package io.securitize.infra.config;

public enum UsersProperty {
    automationMailUsername,
    automationMailPassword,
    automationMailUIPassword,
    automationMail2FaSecret,
    automationCpApiEmail,
    automationCpE2eEmail,
    blackrockCpE2eEmail,
    automationCpPassword,
    automationCp2FaSecret,
    automationCpBearer,
    loginRecaptchaWebsiteKey,
    antiCaptchaClientKey,
    automationCpBearerOperatorId,

    reportsPortalUsername,
    reportsPortalPassword,
    reportsPortalToken,

    visualRegressionBucketName,
    awsProfileName,

    skipUiTestsSpreadsheetId,
    skipApiTestsSpreadsheetId,
    CheckForApiChangesStatusUpdateSpreadsheetId,
    ValidateApiSwaggerMappingsSpreadsheetId,

    skipTestsApiKey,
    googleSheetsKey,

    idologyUsername,
    idologyPassword,

    grafanaUsername,
    grafanaPassword,
    s3fileupdaterurl,

    jenkinsOpsUrl,
    jenkinsOpsUsername,
    jenkinsOpsApiToken,
    jenkinsUsername,
    jenkinsApiToken,


    SecID_IntegrityCheck_Email,
    SecID_IntegrityCheck_AuthorizedBy,
    SecID_IntegrityCheckProd_Email,
    SecID_IntegrityCheckProdATS_Email,
    SecId_EntityInvestor_Email,
    SecID_KycRedirectCheck_Email,
    SecID_SpiceVC_Production_Email,


    marketsOpportunityId,
    blkOpportunityId,

    apiIssuerId,
    apiOperatorEmail,
    apiOperatorPassword,
    apiOperator2FaSecret,
    apiOperatorId,
    apiTokenName,
    apiTokenId,
    apiInvestorEmail,
    apiInvestorPassword,
    apiInvestorId,
    apiOpportunityId,
    apiIssuerURL,
    apiSidSystem,
    apiSidLanguage,
    apiSidName,
    apiSidKey,
    apiSidInvestorId,
    apiSidLivenessInvestorId,
    apiSidUserId,
    apiSidInvestorEmail,
    apiSidInvestorPassword,
    apiSidIssuerSecret,
    apiSidDocumentId,
    apiSidLegalSignerId,
    apiSidLegalSignerDocumentId,
    apiSidConfidentialDocumentId,
    apiSidWallet,
    apiSidWalletsRpcProvider,
    apiSidTokenId,
    apiSidType,
    apiSidRedirectUrl,
    apiSidPermissions,
    apiSidTfaRequestId,
    apiAtsInvestorId,
    apiAtsFundsTransferId,
    apiAtsSecurity,
    apiAtsDeploymentId,
    apiAtsOrderId,
    apiAtsInternalCashTransferId,
    apiAtsQuoteId,
    apiAtsAccountApiKey,
    apiAtsAssetApiKey,
    apiAtsBankApiKey,
    apiAtsConfigApiKey,
    apiAtsOrderApiKey,
    apiAtsReportingApiKey,
    apiAtsGwConnectApiKey,
    apiAtsProviderName,

    //TA
    apiTaW9TaxformId,
    apiTaIssuerId,
    apiTaTokenId,
    apiTaInvestorId,
    apiTaDistributionId,
    dashboardMySqlUrl,
    dashboardMySqlUsername,
    dashboardMySqlPassword,

    browserStackUserName,
    automateUsername,
    automateKey,
    ios_investor_email,
    ios_app_id,

    sandboxBearerToken,

    clusterIp,
    clusterUsername,
    clusterPemPath,
    clusterScriptsPath,
    databaseMySqlUrl,
    databaseMySqlUsername,
    databaseMySqlPassword,
    httpAuthenticationUsername,
    httpAuthenticationPassword,
    httpHeaderNameToAdd,
    httpHeaderValueToAdd,

    defaultPassword,
    defaultPasswordComplex,

    sumSubAppToken,
    sumSubSecretKey,

    algorand_internal_faucet_address,
    algorand_internal_faucet_passphrase,
    algorand_api_address,
    algorand_api_port,
    algorand_api_token,

    pierXAPIKey,
    pierAdminSecret,
    pierDeploymentID,
    pierAPIBaseUrl,

    // BLOCKCHAIN
    bc_issuerId_aut499,
    bc_tokenId_aut499,

    // BLOCKCHAIN - PIER
    pierXApiKey,
    aut611_deploymentId,
    aut611_buyerSecId,
    aut611_sellerSecId,
    aut116_deploymentId,
    aut116_sellerSecId,
    aut116_buyerSecId,
    aut404_identity,
    aut404_holderId,
    aut404_wallet,
    aut404_deploymentId,
    aut429_securitizeId,
    aut429_partnersId,
    aut429_wallet,
    aut473_wallet,
    aut473_identity,
    aut473_deploymentId,
    aut474_deploymentId,
    //BLOCKCHAIN SANITY
    aut696_userFirstName,
    aut696_investorId,
    aut696_issuerId,
    aut696_privateKey,
    aut696_signerAddress,
    aut696_tokenId,
    aut696_investorWallet,
    aut714_userFirstName,
    aut714_investorId,
    aut714_issuerId,
    aut714_privateKey,
    aut714_signerAddress,
    aut714_tokenId,

    // ATS E2E
    ats_default_investor,
    ats_default_tokenSymbol,
    ats_trade_buyInvestor_aut128,
    ats_trade_investor_aut556,
    ats_trade_investorId_aut556,
    ats_trade_buyInvestorId_aut128,
    ats_trade_sellInvestor_aut128,
    ats_trade_sellInvestorId_aut128,
    ats_automationTokenName_aut128,
    ats_automationTokenName_aut556,
    ats_automationTokenName_aut655,
    ats_trade_not_accredited_investor_aut544,
    ats_trade_holding_investor_aut545,
    ats_trade_holding_investorId_aut545,
    ats_trade_investor_aut553_us,
    ats_trade_investor_aut553_spain,
    ats_userAutomationUS,
    ats_userAutomationNonUS,
    ats_passwordUserAutomation,
    ats_apiKey,
    ats_asset,
    ats_investorMail_sanity_flow_prod_aut466,
    ats_investorPass_sanity_flow_prod_aut466,


    // TRANSFER AGENT
    taInvestorGenericPass,
    // TAX FORMS
    taxFormIndividualUSInvestorMail,
    taxFormIndividualUSInvestorSecID,
    taxFormEntityUSInvestorMail,
    taxFormEntityUSInvestorSecID,
    taxFormIndividualNONUSInvestorMail,
    taxFormIndividualNONUSInvestorSecID,
    taxFormEntityNONUSInvestorMail,
    ta_taxforms_ent_nonus_accept_Email_aut491,
    ta_taxforms_ent_nonus_reject_Email_aut492,
    ta_taxforms_ent_nonus_accept_profileId_aut491,
    ta_taxforms_ent_nonus_reject_profileId_aut492,
    taxFormEntityNONUSInvestorSecID,
    ta_redemptionsEntNonUsSecID_aut408,

    // DISTRIBUTIONS
    ta_distribution_testUser_one_aut365,
    ta_distribution_issuerId_aut365,
    ta_distribution_tokenId_aut365,
    ta_distributionGenericInvestorPassword_aut365,
    ta_distributionIssuerProfileEmail_aut365,
    ta_redemptionsIndUsEmail_aut424,
    ta_redemptionsEntNonUsEmail_aut408,
    ta_distributionTestDataFiveEmail_aut365,
    ta_distributionTestDataEightEmail_aut365,
    ta_distributionTestDataNineEmail_aut365,
    ta_distributionTestDataTenEmail_aut424,
    ta_distributionTestDataElevenEmail_aut424,
    ta_distributionTestDataTwelveEmail_aut424,
    ta_distributionTestDataThirteenEmail_aut424,
    ta_distribution_redemption_issuerId_aut476,
    ta_distribution_redemption_tokenId_aut491,
    ta_distribution_redemption_tokenId_aut476,
    ta_distribution_redemption_wallet_aut476,
    ta_distribution_redemption_investor_aut476,
    ta_distribution_redemption_investor_pk_aut476,
    ta_distribution_redemption_token_contract_aut476,
    ta_distribution_redemption_sell_back_price_aut476,
    ta_distribution_redemption_tokens_to_redeem_aut476,
    ta_distribution_redemption_give_back_tokens_aut476,
    ta_distribution_redemption_payment_aut476,
    ta_distribution_redemption_token_price_aut476,
    ta_distribution_redemption_amount_aut476,
    ta_distribution_redemption_initial_payment_aut476,
    ta_distribution_issuerId_aut543,
    ta_distribution_tokenId_aut543,
    ta_distribution_dividend_investorMail_aut543,
    ta_distribution_issuer_CashAccount_Sid_aut365,
    ta_distribution_testUser_one_sid_aut365,

    //ISSUANCE
    ta_issuance_tokenId_aut562,
    ta_issuance_investorId_aut562,
    ta_issuance_wallet_address_aut562,
    ta_issuance_wallet_pk_aut562,
    ta_issuance_investor_email_aut562,

    // DRIP
    ta_issuer_id_aut626,
    ta_token_id_aut626,
    ta_walletAddress_aut626,
    ta_privateKey_aut626,


    // DISTRIBUTIONS EMAIL
    ta_distribution_mail_issuerName,
    // ACCREDITATIONS
    ta_accreditation_individual_aut202,
    ta_accreditation_entity_aut220,
    ta_accreditation_nonus_individual_aut263,
    ta_accreditation_entity_aut271,
    ta_accreditation_individual_aut276,
    ta_accreditation_entity_aut278,
    ta_accreditation_individual_aut279,
    ta_accreditation_entity_aut280,
    ta_accreditation_individual_aut283,
    ta_accreditation_individual_aut284,
    ta_accreditation_entity_aut285,
    ta_accreditation_individual_aut392,
    ta_accreditation_entity_aut393,
    ta_accreditation_individual_aut422,
    ta_accreditation_sanity_prod_aut462,
    ta_accreditation_entity_aut490,
    ta_accreditation_individual_aut503,
    ta_accreditation_entity_aut518,

    //CASH ACCOUNT
    ca_generic_account_password,
    ca_create_account_investor_mail_aut426,
    ca_create_account_investor_mail_aut427,
    ca_create_account_investor_mail_aut428,
    ca_create_account_investor_mail_aut477,
    ca_prime_trust_x_api_key,
    ca_prime_trust_jwt_auth_token,
    ca_prime_trust_create_jwt_api_url,
    ca_create_account_sanity_prod_aut465,
    ca_investorMail_sanity_flow_prod_aut465,
    ca_investorPass_sanity_flow_prod_aut465,
    ca_investor_mail_aut171,
    ca_investor_mail_aut172,
    ca_investor_mail_aut173,
    ca_investor_mail_aut488,
    ca_investor_mail_aut511,
    ca_investor_mail_aut512,
    ca_investor_mail_aut517,
    ca_investor_mail_aut525,
    ca_investor_mail_aut526,
    ca_investor_mail_aut537,
    ca_investor_mail_aut541,
    ca_investor_mail_aut552,
    ca_investor_mail_aut610,
    ca_withdraw_us_wire_account_number,
    ca_withdraw_us_wire_routing_number,
    ca_withdraw_us_wire_international_number,
    ca_withdraw_bic_swift,
    ca_withdraw_bank_name,
    ca_withdraw_intermediary_bank_account_number,
    ca_withdraw_intermediary_bank_name,
    ca_withdraw_intermediary_bank_address,
    ca_withdraw_intermediary_bank_city,
    ca_withdraw_intermediary_bank_country,
    ca_withdraw_intermediary_bank_state,
    ca_withdraw_intermediary_bank_zipCode,
    ca_gw_api_mail,


    ta_accreditation_individual_aut475,
    //CASH ACCOUNT API
    ca_api_investorId,
    ca_config_xApiKey,
    ca_exchange_xApiKey,
    ca_investor_xApiKey,
    ca_transaction_xApiKey,
    ca_transfer_method_xApiKey,
    caInvestorApiKey,
    apiCaBankSynapseApiKey,
    ca_bank_zerohash_xApiKey,
    ca_api_providerId,
    ca_api_cashAccountId,

    // FUNDRAISE
    ft_issuerId_aut274,
    ft_tokenId_aut274,
    ft_issuerNieUrl_aut516,
    ft_issuerId_aut516,
    ft_tokenId_aut516,
    ft_issuerId_aut524,
    ft_tokenId_aut524,
    ft_issuerNieUrl_aut524,
    ft_issuerId_aut539,
    ft_tokenId_aut539,
    ft_issuerNieUrl_aut539,
    AUT617_Security_RateLimiting_User_email,
    ft_issuerId_aut548,
    ft_tokenId_aut548,
    ft_issuerNieUrl_aut548,

    // Japan
    jp_mailUsername,
    jp_mailPassword,
    jp_domainApiBaseUrl,
    jp_domainApiKey,
    marui_investorSiteBaseUrl,
    marui_domainId,
    marui_tokenId,
    marui_issuerFullName,
    marui_newInvestorEmail,
    marui_existingInvestorEmail,
    marui_investorPassword,
    marui_adminEmail,
    marui_adminPassword,
    marui_adminMfaSecret,
    sonyAdminEmail,
    sonyAdminPassword,
    sonyAdminMfaSecret,
    sonySsoSecret,
    sonySsoSalt,
    sonySsoHashIterations,
    sonyInvestorSiteBaseUrl,
    sonyDomainId,
    smtb1AdminEmail,
    smtb1AdminPassword,
    smtb1AdminMfaSecret,
    smtb2AdminEmail,
    smtb2AdminPassword,
    smtb2AdminMfaSecret,
    jpOp03AdminEmail,
    jpOp03AdminPassword,
    jpOp03AdminMfaSecret,
    jpOp04AdminEmail,
    jpOp04AdminPassword,
    jpOp04AdminMfaSecret,

    confluentCloudBaseUrl,
    confluentCloudAutomationKey,
    confluentCloudAutomationSecret,
    confluentCloudAutomationClusterId,

    bitbucketEventsPkgUrl,
    bitbucketUsername,
    bitbucketPassword,

    blackrockHolderWalletPrivateKey,
    blackrockAuthorizedRecipientAddress
}
