package io.securitize.scripts;

import io.securitize.infra.api.CashAccountApi;
import io.securitize.infra.api.InvestorsAPI;
import io.securitize.tests.InvestorDetails;
import io.securitize.tests.abstractClass.AbstractTest;
import org.testng.annotations.Test;

import static io.securitize.infra.reporting.MultiReporter.info;

public class AUT521_CA_API_CreateSidAndCashAccount extends AbstractTest {

    CashAccountApi cashAccountApi;

    public AUT521_CA_API_CreateSidAndCashAccount() {
        cashAccountApi = new CashAccountApi();
    }

    @Test
    public void createSidInvestorWithCashAccount() throws Exception {

        // Set the desired country and ticket number here
        // email address will have the following format: securitize_automation+ticketNumber@securitize.io
        String investorId = createSid("United States of America", "ca_rc_jenkins_004");

        Double fundingAmount = 10000.35;
        String cashAccount = createCashAccountWithFunds(investorId, fundingAmount);

        System.out.println("InvestorId: " + investorId);
        System.out.println("CashAccountId: " + cashAccount);
    }

    /**
     * This method is to create a Securitize account.
     *
     * @param country      if null, by default is United States of America
     * @param ticketNumber if null, autogenerated email address
     * @return investorId
     */
    public String createSid(String country, String ticketNumber) throws Exception {

        InvestorDetails investorDetails = InvestorDetails.generateRandomUSInvestor();

        if (ticketNumber != null) {
            String mail = "securitize_automation+" + ticketNumber + "@securitize.io";
            investorDetails.setEmail(mail);
        }

        if (country == null) {
            // By default, country is United States of America
            investorDetails.setCountryOfBirth(investorDetails.getCountryOfTax());
        } else {
            investorDetails.setCountryOfBirth(country);
            investorDetails.setCountry(country);
            investorDetails.setCountryOfTax(country);
        }

        // Setting State to Alaska because with default value (New York) account creation fails.
        investorDetails.setState("Alaska");

        investorDetails.setFirstName("Securitize");
        investorDetails.setMiddleName(null);
        investorDetails.setLastName("Automation");

        InvestorsAPI investorsAPI = new InvestorsAPI();

        return investorsAPI.createNewSecuritizeIdInvestor(investorDetails);

    }

    public String getInvestorIdByEmail(String email){
        InvestorsAPI investorsAPI = new InvestorsAPI();
        String investorId = investorsAPI.getUniqueSecuritizeIdByEmail(email);
        info("InvestorId: " + investorId + " for email: " + email);
        return investorId;
    }

    public String createCashAccountWithFunds(String investorId, Double fundingAmount) {
        return cashAccountApi.createCashAccountWithFunds(investorId, fundingAmount);
    }

    public String deleteCashAccount(String cashAccountId){
        info("Deleting account with CashAccountId: " + cashAccountId);
        return cashAccountApi.deleteCashAccount(cashAccountId);
    }

    public String getCashAccountId(String investorId) {
        return cashAccountApi.getCashAccountId(investorId);
    }
}